/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pSmile_PSmile */

#ifndef _Included_pSmile_PSmile
#define _Included_pSmile_PSmile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pSmile_PSmile
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_pSmile_PSmile_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pSmile_PSmile
 * Method:    findSmile
 * Signature: ([FII)F
 */
JNIEXPORT jfloat JNICALL Java_pSmile_PSmile_findSmile
  (JNIEnv *, jobject, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
